export const elements = {
  userLoginIcon: '#menuUserLink',
  username: 'input[name="username"]',
  password: 'input[name="password"]',
  mensageUserRequired: '.inputContainer > label.invalid',
  laptopImageId: '#laptopsImg',
  laptopProductId: '#\\36 ',
  addMoreQuantity: '.plus',
  addToCart: '[name="save_to_cart"]',
  shoppingCartLink: '#shoppingCartLink',
  cartProductQuantity: 'td:nth-child(5) > label.ng-binding',
  btnRegistration: '#registration_btn',
  username: '[name="usernameRegisterPage"]',
  email: '[name="emailRegisterPage"]',
  password: '[name="passwordRegisterPage"]',
  confirmPassword: '[name="confirm_passwordRegisterPage"]',
  firstName: '[name="first_nameRegisterPage"]',
  lastName: '[name="last_nameRegisterPage"]',
  phoneNumber: '[name="phone_numberRegisterPage"]',
  country: '[name="countryListboxRegisterPage"]',
  city: '[name="cityRegisterPage"]',
  address: '[name="addressRegisterPage"]',
  state: '[name="state_/_province_/_regionRegisterPage"]',
  postalCode: '[name="postal_codeRegisterPage"]',
  registerUsername: '[name="usernameRegisterPage"]',
  registerEmail: '[name="emailRegisterPage"]',
  registerPassword: '[name="passwordRegisterPage"]',
  registerConfirmPassword: '[name="confirm_passwordRegisterPage"]',
  registerFirstName: '[name="first_nameRegisterPage"]',
  registerLastName: '[name="last_nameRegisterPage"]',
  registerPhoneNumber: '[name="phone_numberRegisterPage"]',
  registerCountry: '[name="countryListboxRegisterPage"]',
  registerCity: '[name="cityRegisterPage"]',
  registerAddress: '[name="addressRegisterPage"]',
  registerState: '[name="state_/_province_/_regionRegisterPage"]',
  registerPostalCode: '[name="postal_codeRegisterPage"]',
  agreeTerms: '[name="i_agree"]',
  btnRegister: '#register_btn',
  btnNext: '.mobileBtnHandler > #next_btn',
  safepayUsername: '[name="safepay_username"]',
  safepayPassword: '[name="safepay_password"]',
  btnSaveSafepay: '[name="save_safepay"]',
  btnPayNow: '#pay_now_btn_SAFEPAY'
};
